### ISSUE TITLE
API에 접근 할 수 없음

### ISSUE THREAD

**Issue by JellyBrick** [JellyBrick/Koreanbots-Kotlin-SDK#29]
`v2` API에 접근이 불가능해진 것으로 보임

**Comment by ghost** [comment]
API v2는 현재 서비스 되고 있지 않습니다.
`beta.koreanbots.dev/api/v2`에서 서비스 되고는 있습니다만 베타 테스트용이며 따라서 실서비스에 적용되지는 않습니다.
다만, API v1이 Docs와 다르게 작동하므로 기존의 v1 코드 또한 작동하지 않는 상태입니다.
따라서, `revert`도 의미가 없다고 생각되기는 합니다.

**Comment by ghost** [comment]
https://github.com/JellyBrick/Koreanbots-Kotlin-SDK/pull/30

**Comment by nkgcp** [comment]
근데 v2가 이번주 토요일 릴리즈네요
v1 지원하는 의미가 있을까요?

**Comment by nkgcp** [comment]
코드는 버리셔도 될 것 같네요

**Comment by ghost** [comment]
v2 릴리즈 되었습니다. 코드는 버리셔도 될 것 같고, 정상 작동만 확인해보면 되겠네요.
테스트 코드라도 작성해야할까요?
