### ISSUE TITLE
Compatibility 버전 질문

### ISSUE THREAD

**Issue by ghost** [JellyBrick/Koreanbots-Kotlin-SDK#32]
제가 잘 몰라서 그러는데 빌드 스크립트에 Compatibility를 전부 1.7로 하신 이유가 있나요?
Compatibility가 1.7이면 `junit-platform`이 인식이 안되더라고요.

**Comment by JellyBrick** [comment]
junit-jupiter와 kotlin-test-junit5 쓰시면 될 것 같습니다.

**Comment by ghost** [comment]
`junit-jupiter`도 같은 이유로 인식되지 않습니다

**Comment by ghost** [comment]
혹시 `jackson-databind`의 호환성이 1.7이라서 그러신가요?
`jackson-databind`는 2.12 버전부터 최소 호환성을 1.8로 변경했고,
`jackson-module-kotlin`도 1.7을 버리고 1.8을 타겟으로 설정하고 있습니다.

그리고 코틀린 `jvmTarget`도 1.6으로 해놓으셨는데 그 이유가 있으신지요.
1.5.0부터는 1.6 타겟이 Deprecated되고 기본이 1.8로 변경되었습니다.

**Comment by JellyBrick** [comment]
> 혹시 `jackson-databind`의 호환성이 1.7이라서 그러신가요?
> `jackson-databind`는 2.12 버전부터 최소 호환성을 1.8로 변경했고,
> `jackson-module-kotlin`도 1.7을 버리고 1.8을 타겟으로 설정하고 있습니다.
> 
> 그리고 코틀린 `jvmTarget`도 1.6으로 해놓으셨는데 그 이유가 있으신지요.
> 1.5.0부터는 1.6 타겟이 Deprecated되고 기본이 1.8로 변경되었습니다.

eb61f9e681aa1cbf15e3e1b42855706a7b970f73

구형 안드로이드 기기에서도 라이브러리를 문제없이 사용할 수 있도록, target을 1.7로 지정해두었으나
의미가 없다고 판단되어 1.8로 변경 완료했습니다.
